version: '3'

services:
  app:
    build: ./backend/django_project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/django_project/:/usr/src/app